### ISSUE TITLE
Realtime Doppler

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-weather#1]
## Tasks
- [ ] Finish Doppler realtime on OSH server
- [ ] ddelete files immediately after processing
- [ ] allow dynamic adding of radar sites
- [ ] improve logic when scans are missed
- [x] figure out why new queue isn't created upon new request after idle timeout periods
