### ISSUE TITLE
METAR Stations

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-weather#3]
## Tasks
- [x] Integrate new parser into driver
- [x] modify driver to ingest files from WxEmwin software
- [ ] modify driver to work as SOS-T client and push obs to upstream node
