### ISSUE TITLE
Vaisala

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-weather#4]
## Tasks to deploy

- [x] Finish Vaisala drivers for OSH
- [ ] Deploy Vaisala sensor on roof
- [ ] Enable OSH Node for weather
- [ ] Show weather in client
